/* Generated By:JavaCC: Do not edit this line. PromelaConstants.java */
package spinja.promela.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PromelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROCTYPE = 1;
  /** RegularExpression Id. */
  int INIT = 2;
  /** RegularExpression Id. */
  int NEVER = 3;
  /** RegularExpression Id. */
  int TRACE = 4;
  /** RegularExpression Id. */
  int NOTRACE = 5;
  /** RegularExpression Id. */
  int TYPEDEF = 6;
  /** RegularExpression Id. */
  int MTYPE = 7;
  /** RegularExpression Id. */
  int BIT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int BYTE = 10;
  /** RegularExpression Id. */
  int PID = 11;
  /** RegularExpression Id. */
  int SHORT = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int CHAN = 14;
  /** RegularExpression Id. */
  int ACTIVE = 15;
  /** RegularExpression Id. */
  int PRIORITY = 16;
  /** RegularExpression Id. */
  int PROVIDED = 17;
  /** RegularExpression Id. */
  int HIDDEN = 18;
  /** RegularExpression Id. */
  int SHOW = 19;
  /** RegularExpression Id. */
  int XR = 20;
  /** RegularExpression Id. */
  int XS = 21;
  /** RegularExpression Id. */
  int OF = 22;
  /** RegularExpression Id. */
  int EVAL = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int FI = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int OD = 27;
  /** RegularExpression Id. */
  int ATOMIC = 28;
  /** RegularExpression Id. */
  int D_STEP = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int BREAK = 31;
  /** RegularExpression Id. */
  int GOTO = 32;
  /** RegularExpression Id. */
  int PRINT = 33;
  /** RegularExpression Id. */
  int ASSERT = 34;
  /** RegularExpression Id. */
  int LEN = 35;
  /** RegularExpression Id. */
  int TIMEOUT = 36;
  /** RegularExpression Id. */
  int NP_ = 37;
  /** RegularExpression Id. */
  int ENABLED = 38;
  /** RegularExpression Id. */
  int PC_VALUE = 39;
  /** RegularExpression Id. */
  int RUN = 40;
  /** RegularExpression Id. */
  int FULL = 41;
  /** RegularExpression Id. */
  int EMPTY = 42;
  /** RegularExpression Id. */
  int NFULL = 43;
  /** RegularExpression Id. */
  int NEMPTY = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int FALSE = 46;
  /** RegularExpression Id. */
  int SKIP_ = 47;
  /** RegularExpression Id. */
  int UNLESS = 48;
  /** RegularExpression Id. */
  int VAR_PID = 49;
  /** RegularExpression Id. */
  int LCURLY = 50;
  /** RegularExpression Id. */
  int RCURLY = 51;
  /** RegularExpression Id. */
  int ASSIGN = 52;
  /** RegularExpression Id. */
  int LPAREN = 53;
  /** RegularExpression Id. */
  int RPAREN = 54;
  /** RegularExpression Id. */
  int LBRACK = 55;
  /** RegularExpression Id. */
  int RBRACK = 56;
  /** RegularExpression Id. */
  int OPTION = 57;
  /** RegularExpression Id. */
  int COLON = 58;
  /** RegularExpression Id. */
  int SEMICOLON = 59;
  /** RegularExpression Id. */
  int COMMA = 60;
  /** RegularExpression Id. */
  int RARROW = 61;
  /** RegularExpression Id. */
  int CH_SEND_SORTED = 62;
  /** RegularExpression Id. */
  int CH_READ = 63;
  /** RegularExpression Id. */
  int CH_READ_RAND = 64;
  /** RegularExpression Id. */
  int AT = 65;
  /** RegularExpression Id. */
  int BNOT = 66;
  /** RegularExpression Id. */
  int LNOT = 67;
  /** RegularExpression Id. */
  int MINUS = 68;
  /** RegularExpression Id. */
  int TIMES = 69;
  /** RegularExpression Id. */
  int DIVIDE = 70;
  /** RegularExpression Id. */
  int MODULO = 71;
  /** RegularExpression Id. */
  int PLUS = 72;
  /** RegularExpression Id. */
  int LSHIFT = 73;
  /** RegularExpression Id. */
  int RSHIFT = 74;
  /** RegularExpression Id. */
  int LT = 75;
  /** RegularExpression Id. */
  int LTE = 76;
  /** RegularExpression Id. */
  int GT = 77;
  /** RegularExpression Id. */
  int GTE = 78;
  /** RegularExpression Id. */
  int EQ = 79;
  /** RegularExpression Id. */
  int NEQ = 80;
  /** RegularExpression Id. */
  int BAND = 81;
  /** RegularExpression Id. */
  int XOR = 82;
  /** RegularExpression Id. */
  int BOR = 83;
  /** RegularExpression Id. */
  int LAND = 84;
  /** RegularExpression Id. */
  int LOR = 85;
  /** RegularExpression Id. */
  int INCR = 86;
  /** RegularExpression Id. */
  int DECR = 87;
  /** RegularExpression Id. */
  int DOT = 88;
  /** RegularExpression Id. */
  int IDENTIFIER = 89;
  /** RegularExpression Id. */
  int NUMBER = 90;
  /** RegularExpression Id. */
  int STRING = 100;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"proctype\"",
    "\"init\"",
    "\"never\"",
    "\"trace\"",
    "\"notrace\"",
    "\"typedef\"",
    "\"mtype\"",
    "\"bit\"",
    "\"bool\"",
    "\"byte\"",
    "\"pid\"",
    "\"short\"",
    "\"int\"",
    "\"chan\"",
    "\"active\"",
    "\"priority\"",
    "\"provided\"",
    "\"hidden\"",
    "\"show\"",
    "\"xr\"",
    "\"xs\"",
    "\"of\"",
    "\"eval\"",
    "\"if\"",
    "\"fi\"",
    "\"do\"",
    "\"od\"",
    "\"atomic\"",
    "\"d_step\"",
    "\"else\"",
    "\"break\"",
    "\"goto\"",
    "\"printf\"",
    "\"assert\"",
    "\"len\"",
    "\"timeout\"",
    "\"np_\"",
    "\"enabled\"",
    "\"pc_value\"",
    "\"run\"",
    "\"full\"",
    "\"empty\"",
    "\"nfull\"",
    "\"nempty\"",
    "\"true\"",
    "\"false\"",
    "\"skip\"",
    "\"unless\"",
    "\"_pid\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"->\"",
    "\"!!\"",
    "\"?\"",
    "\"??\"",
    "\"@\"",
    "\"~\"",
    "\"!\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"<<\"",
    "\">>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"^\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "<token of kind 96>",
    "\"*/\"",
    "\"\\\"\"",
    "<token of kind 99>",
    "\"\\\"\"",
  };

}
