/* Generated By:JavaCC: Do not edit this line. PromelaConstants.java */
package spins.promela.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PromelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROCTYPE = 1;
  /** RegularExpression Id. */
  int INIT = 2;
  /** RegularExpression Id. */
  int NEVER = 3;
  /** RegularExpression Id. */
  int TRACE = 4;
  /** RegularExpression Id. */
  int NOTRACE = 5;
  /** RegularExpression Id. */
  int TYPEDEF = 6;
  /** RegularExpression Id. */
  int MTYPE = 7;
  /** RegularExpression Id. */
  int BIT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int BYTE = 10;
  /** RegularExpression Id. */
  int PID = 11;
  /** RegularExpression Id. */
  int SHORT = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int CHAN = 14;
  /** RegularExpression Id. */
  int PRIORITY = 15;
  /** RegularExpression Id. */
  int PROVIDED = 16;
  /** RegularExpression Id. */
  int HIDDEN = 17;
  /** RegularExpression Id. */
  int SHOW = 18;
  /** RegularExpression Id. */
  int XR = 19;
  /** RegularExpression Id. */
  int XS = 20;
  /** RegularExpression Id. */
  int OF = 21;
  /** RegularExpression Id. */
  int EVAL = 22;
  /** RegularExpression Id. */
  int FOR = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int FI = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int OD = 27;
  /** RegularExpression Id. */
  int ATOMIC = 28;
  /** RegularExpression Id. */
  int D_STEP = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int BREAK = 31;
  /** RegularExpression Id. */
  int GOTO = 32;
  /** RegularExpression Id. */
  int PRINT = 33;
  /** RegularExpression Id. */
  int ASSERT = 34;
  /** RegularExpression Id. */
  int LEN = 35;
  /** RegularExpression Id. */
  int TIMEOUT = 36;
  /** RegularExpression Id. */
  int NP_ = 37;
  /** RegularExpression Id. */
  int ENABLED = 38;
  /** RegularExpression Id. */
  int PC_VALUE = 39;
  /** RegularExpression Id. */
  int RUN = 40;
  /** RegularExpression Id. */
  int FULL = 41;
  /** RegularExpression Id. */
  int EMPTY = 42;
  /** RegularExpression Id. */
  int NFULL = 43;
  /** RegularExpression Id. */
  int NEMPTY = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int FALSE = 46;
  /** RegularExpression Id. */
  int SKIP_ = 47;
  /** RegularExpression Id. */
  int UNLESS = 48;
  /** RegularExpression Id. */
  int VAR_PID = 49;
  /** RegularExpression Id. */
  int VAR_NR_PR = 50;
  /** RegularExpression Id. */
  int LCURLY = 51;
  /** RegularExpression Id. */
  int RCURLY = 52;
  /** RegularExpression Id. */
  int ASSIGN = 53;
  /** RegularExpression Id. */
  int LPAREN = 54;
  /** RegularExpression Id. */
  int RPAREN = 55;
  /** RegularExpression Id. */
  int LBRACK = 56;
  /** RegularExpression Id. */
  int RBRACK = 57;
  /** RegularExpression Id. */
  int OPTION = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int SEMICOLON = 60;
  /** RegularExpression Id. */
  int COMMA = 61;
  /** RegularExpression Id. */
  int RARROW = 62;
  /** RegularExpression Id. */
  int CH_SEND_SORTED = 63;
  /** RegularExpression Id. */
  int CH_READ = 64;
  /** RegularExpression Id. */
  int CH_READ_RAND = 65;
  /** RegularExpression Id. */
  int AT = 66;
  /** RegularExpression Id. */
  int BNOT = 67;
  /** RegularExpression Id. */
  int LNOT = 68;
  /** RegularExpression Id. */
  int MINUS = 69;
  /** RegularExpression Id. */
  int TIMES = 70;
  /** RegularExpression Id. */
  int DIVIDE = 71;
  /** RegularExpression Id. */
  int MODULO = 72;
  /** RegularExpression Id. */
  int PLUS = 73;
  /** RegularExpression Id. */
  int LSHIFT = 74;
  /** RegularExpression Id. */
  int RSHIFT = 75;
  /** RegularExpression Id. */
  int LT = 76;
  /** RegularExpression Id. */
  int LTE = 77;
  /** RegularExpression Id. */
  int GT = 78;
  /** RegularExpression Id. */
  int GTE = 79;
  /** RegularExpression Id. */
  int EQ = 80;
  /** RegularExpression Id. */
  int NEQ = 81;
  /** RegularExpression Id. */
  int BAND = 82;
  /** RegularExpression Id. */
  int XOR = 83;
  /** RegularExpression Id. */
  int BOR = 84;
  /** RegularExpression Id. */
  int LAND = 85;
  /** RegularExpression Id. */
  int LOR = 86;
  /** RegularExpression Id. */
  int INCR = 87;
  /** RegularExpression Id. */
  int DECR = 88;
  /** RegularExpression Id. */
  int DOT = 89;
  /** RegularExpression Id. */
  int IDENTIFIER = 99;
  /** RegularExpression Id. */
  int NUMBER = 100;
  /** RegularExpression Id. */
  int DEFINE = 189;
  /** RegularExpression Id. */
  int PARAM = 194;
  /** RegularExpression Id. */
  int STRING = 216;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;
  /** Lexical state. */
  int IN_COMMENT2 = 3;
  /** Lexical state. */
  int PREPROCESSOR_INCLUDE_FILE = 4;
  /** Lexical state. */
  int PREPROCESSOR_INCLUDE = 5;
  /** Lexical state. */
  int PREPROCESSOR_DEFINE_REST = 6;
  /** Lexical state. */
  int PREPROCESSOR_DEFINE_PARAM2 = 7;
  /** Lexical state. */
  int PREPROCESSOR_DEFINE_PARAM1 = 8;
  /** Lexical state. */
  int PREPROCESSOR_DEFINE_PARAM = 9;
  /** Lexical state. */
  int PREPROCESSOR_DEFINE = 10;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_REST = 11;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_TEXT = 12;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_PARAM2 = 13;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_PARAM1 = 14;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_PARAM0 = 15;
  /** Lexical state. */
  int PREPROCESSOR_INLINE_PARAM = 16;
  /** Lexical state. */
  int PREPROCESSOR_INLINE = 17;
  /** Lexical state. */
  int PREPROCESSOR_LINE = 18;
  /** Lexical state. */
  int PREPROCESSOR_FILE = 19;
  /** Lexical state. */
  int PREPROCESSOR_ELIF_SKIP = 20;
  /** Lexical state. */
  int PREPROCESSOR_SKIP = 21;
  /** Lexical state. */
  int PREPROCESSOR_IFNDEF = 22;
  /** Lexical state. */
  int PREPROCESSOR_IFDEF = 23;
  /** Lexical state. */
  int PREPROCESSOR_IF = 24;
  /** Lexical state. */
  int PREPROCESSOR_NDEFINED = 25;
  /** Lexical state. */
  int PREPROCESSOR_DEFINED = 26;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"proctype\"",
    "\"init\"",
    "\"never\"",
    "\"trace\"",
    "\"notrace\"",
    "\"typedef\"",
    "\"mtype\"",
    "\"bit\"",
    "\"bool\"",
    "\"byte\"",
    "\"pid\"",
    "\"short\"",
    "\"int\"",
    "\"chan\"",
    "\"priority\"",
    "\"provided\"",
    "\"hidden\"",
    "\"show\"",
    "\"xr\"",
    "\"xs\"",
    "\"of\"",
    "\"eval\"",
    "\"for\"",
    "\"if\"",
    "\"fi\"",
    "\"do\"",
    "\"od\"",
    "\"atomic\"",
    "\"d_step\"",
    "\"else\"",
    "\"break\"",
    "\"goto\"",
    "\"printf\"",
    "\"assert\"",
    "\"len\"",
    "\"timeout\"",
    "\"np_\"",
    "\"enabled\"",
    "\"pc_value\"",
    "\"run\"",
    "\"full\"",
    "\"empty\"",
    "\"nfull\"",
    "\"nempty\"",
    "\"true\"",
    "\"false\"",
    "\"skip\"",
    "\"unless\"",
    "\"_pid\"",
    "\"_nr_pr\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"->\"",
    "\"!!\"",
    "\"?\"",
    "\"??\"",
    "\"@\"",
    "\"~\"",
    "\"!\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"<<\"",
    "\">>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"^\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "\"inline\"",
    "\"defined\"",
    "\"ndef\"",
    "\"(\"",
    "\" \"",
    "<token of kind 95>",
    "\"(\"",
    "\" \"",
    "<token of kind 98>",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"#if\"",
    "\"#ifdef\"",
    "\"#ifndef\"",
    "\"#else\"",
    "\"#elif\"",
    "\"#endif\"",
    "\"#line\"",
    "\"#file\"",
    "\"#define\"",
    "\"#include\"",
    "\"#\"",
    "<token of kind 118>",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 122>",
    "<token of kind 123>",
    "<token of kind 124>",
    "<token of kind 125>",
    "<token of kind 126>",
    "<token of kind 127>",
    "\"#else\"",
    "\"#elif\"",
    "\"#endif\"",
    "<token of kind 131>",
    "<token of kind 132>",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 136>",
    "<token of kind 137>",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 141>",
    "<token of kind 142>",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 146>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 152>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"(\"",
    "<token of kind 159>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 165>",
    "\")\"",
    "<token of kind 167>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 173>",
    "<token of kind 174>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\",\"",
    "\")\"",
    "<token of kind 182>",
    "<token of kind 183>",
    "\"{\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 187>",
    "<token of kind 188>",
    "<DEFINE>",
    "<token of kind 190>",
    "\"(\"",
    "<token of kind 192>",
    "<token of kind 193>",
    "<PARAM>",
    "<token of kind 195>",
    "<token of kind 196>",
    "\",\"",
    "\")\"",
    "<token of kind 199>",
    "<token of kind 200>",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 204>",
    "<token of kind 205>",
    "\"\\\"\"",
    "\"\\\"\"",
    "<token of kind 208>",
    "<token of kind 209>",
    "<token of kind 210>",
    "\"/*\"",
    "<token of kind 212>",
    "\"*/\"",
    "\"\\\"\"",
    "<token of kind 215>",
    "\"\\\"\"",
  };

}
